"""Initial migration

Revision ID: 142fca2bd4e9
Revises: 
Create Date: 2026-03-30 13:08:37.656065
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '142fca2bd4e9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_images',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('registry_path', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Enum('CATALOG', 'ADAPTED', 'GENERATED', name='image_source'), nullable=False),
    sa.Column('build_status', sa.Enum('READY', 'BUILDING', 'FAILED', name='build_status'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_images_content_hash'), 'container_images', ['content_hash'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'CONTRIBUTOR', 'BOTH', name='user_role'), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('credit_balance', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('RENDER', 'DATA', 'ML_TRAINING', 'SIMULATION', name='job_type'), nullable=True),
    sa.Column('status', sa.Enum('ANALYZING', 'QUEUED', 'RUNNING', 'ASSEMBLING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('ml_sync_mode', sa.Enum('DDP', 'LOCAL_SGD', name='ml_sync_mode'), nullable=True),
    sa.Column('container_image', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('cost_estimate', sa.JSON(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('completed_chunks', sa.Integer(), nullable=False),
    sa.Column('input_path', sa.String(length=512), nullable=True),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.Column('presigned_url', sa.String(length=2048), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Float(), nullable=False),
    sa.Column('gpu_model', sa.String(length=100), nullable=False),
    sa.Column('gpu_vram_gb', sa.Float(), nullable=False),
    sa.Column('cuda_version', sa.String(length=20), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('total_earned', sa.Float(), nullable=False),
    sa.Column('total_gpu_hours', sa.Float(), nullable=False),
    sa.Column('bandwidth_mbps', sa.Float(), nullable=False),
    sa.Column('cert_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'BUSY', 'OFFLINE', 'SUSPENDED', name='node_status'), nullable=False),
    sa.Column('resource_limits', sa.JSON(), nullable=True),
    sa.Column('cached_images', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_contribution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'RUNNING', 'COMPLETED', 'FAILED', 'REQUEUED', name='chunk_status'), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('checkpoint_path', sa.String(length=512), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('gpu_hours', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('estimated_seconds', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_records',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('contributor_id', sa.Uuid(), nullable=False),
    sa.Column('gpu_hours', sa.Float(), nullable=False),
    sa.Column('customer_charge', sa.Float(), nullable=False),
    sa.Column('contributor_credit', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('dynamic_multiplier', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_records')
    op.drop_table('chunks')
    op.drop_table('nodes')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_container_images_content_hash'), table_name='container_images')
    op.drop_table('container_images')
    # ### end Alembic commands ###
