"""add requires_public_network to jobs

Revision ID: 786f26d5b694
Revises: 142fca2bd4e9
Create Date: 2026-04-03 23:37:32.383860
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786f26d5b694'
down_revision: Union[str, None] = '142fca2bd4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('requires_public_network', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'requires_public_network')
    # ### end Alembic commands ###
